# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

stages:
    - instalacion
    - build
    - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

instalacion:
  stage: instalacion  
  script:
    - npm install || true
    

build:
  stage: build
  script:
    - npm run build
    
deploy:
  stage: deploy
  script:
    - npm run dist  
  artifacts:
    paths: 
      - '/dist'
     

